[build]
  command = "npm run build"
  publish = ".svelte-kit/output"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "#custom"

[functions]
  directory = ".netlify/functions"

[images]
  remote_images = ["https://ext.same-assets.com/*", "https://same-assets.com/*"]
